// ========================================
// AI Ideas - Ide Konten Generator
// ========================================

// Fungsi untuk initialize halaman ideas
function initializeIdeasPage() {
    console.log('💡 Initializing AI Ideas page');
    
    // Setup form submit event
    const form = document.getElementById('ideasForm');
    if (form) {
        form.addEventListener('submit', handleIdeasSubmit);
    }
}

// Handle form submit untuk generate ideas
function handleIdeasSubmit(event) {
    event.preventDefault();
    
    // Ambil form data
    const formData = {
        businessType: document.getElementById('businessType').value,
        contentGoal: document.getElementById('contentGoal').value,
        platform: document.getElementById('platform').value
    };
    
    // Validate form
    const validation = Utils.validateFormData(formData, ['businessType', 'contentGoal', 'platform']);
    
    if (!validation.isValid) {
        Utils.showToast('❌ ' + validation.errors[0]);
        return;
    }
    
    // Generate ideas
    generateIdeas(formData);
}

// Fungsi utama untuk generate ideas
function generateIdeas(formData) {
    console.log('🔄 Generating ideas with data:', formData);
    
    // Show loading
    Utils.showButtonLoading('generateBtn', 'Generating...');
    Utils.showElement('loadingIdeas');
    Utils.hideElement('ideasResults');
    
    // Simulasi API call (akan diganti dengan real API)
    // Untuk sekarang, kita gunakan dummy data
    setTimeout(() => {
        const dummyIdeas = getDummyIdeas(formData);
        displayIdeas(dummyIdeas);
        
        // Hide loading
        Utils.hideButtonLoading('generateBtn', 'Generate Ide Konten');
        Utils.hideElement('loadingIdeas');
    }, 2000);
}

// Fungsi untuk display ideas results
function displayIdeas(ideas) {
    const resultsContainer = document.getElementById('ideasResults');
    const ideasList = document.getElementById('ideasList');
    
    if (!resultsContainer || !ideasList) {
        console.error('Results container not found');
        return;
    }
    
    // Clear previous results
    ideasList.innerHTML = '';
    
    // Generate HTML untuk setiap idea
    ideas.forEach((idea, index) => {
        const ideaCard = createIdeaCard(idea, index);
        ideasList.appendChild(ideaCard);
    });
    
    // Show results dengan fade-in
    Utils.showElement('ideasResults');
    Utils.scrollToElement('ideasResults', 100);
    
    console.log(`✅ Displayed ${ideas.length} ideas`);
}

// Fungsi untuk create idea card element
function createIdeaCard(idea, index) {
    const card = document.createElement('div');
    card.className = 'idea-card';
    card.setAttribute('data-index', index);
    
    card.innerHTML = `
        <div class="idea-title">${idea.title}</div>
        <div class="idea-description">${idea.description}</div>
        <div class="idea-meta">
            <span class="meta-item">📱 ${idea.platform}</span>
            <span class="meta-item">🎯 ${idea.format}</span>
            <span class="meta-item">📊 ${Math.round(idea.confidence * 100)}%</span>
        </div>
        <button class="btn btn-copy" onclick="copyIdea(${index})">
            📋 Copy Ide Ini
        </button>
    `;
    
    return card;
}

// Fungsi untuk copy idea
function copyIdea(index) {
    const ideas = window.currentIdeas || [];
    const idea = ideas[index];
    
    if (!idea) {
        Utils.showToast('❌ Ide tidak ditemukan');
        return;
    }
    
    // Format idea untuk copy
    const ideaText = `💡 ${idea.title}

${idea.description}

📱 Platform: ${idea.platform}
🎯 Format: ${idea.format}
📊 Confidence: ${Math.round(idea.confidence * 100)}%

--- Generated by AI UMKM ---`;
    
    // Copy ke clipboard
    copyTextToClipboard(ideaText);
}

// Fungsi untuk copy text langsung
function copyTextToClipboard(text) {
    if (navigator.clipboard && window.isSecureContext) {
        navigator.clipboard.writeText(text).then(() => {
            Utils.showToast('✅ Ide berhasil disalin ke clipboard!');
        }).catch(err => {
            console.error('Copy failed:', err);
            Utils.showToast('❌ Gagal menyalin ide');
        });
    } else {
        // Fallback untuk browser lama
        const textArea = document.createElement('textarea');
        textArea.value = text;
        document.body.appendChild(textArea);
        textArea.select();
        
        try {
            document.execCommand('copy');
            Utils.showToast('✅ Ide berhasil disalin ke clipboard!');
        } catch (err) {
            Utils.showToast('❌ Gagal menyalin ide');
        }
        
        document.body.removeChild(textArea);
    }
}

// Dummy data untuk testing (akan diganti dengan real API)
function getDummyIdeas(formData) {
    const { businessType, contentGoal, platform } = formData;
    
    // Sample ideas berdasarkan input
    const baseIdeas = {
        makanan: {
            jualan: [
                {
                    title: "Behind The Scene Masak",
                    description: "Tunjukkan proses pembuatan makanan dari awal sampai jadi. Bikin video 15-30 detik dengan ASMR suara masakan.",
                    platform: platform,
                    format: platform === 'TikTok' ? 'Video Pendek' : 'Reels',
                    confidence: 0.89
                },
                {
                    title: "Review Pelanggan Real Time",
                    description: "Posting foto makanan yang lagi dimakan pelanggan + caption testimoninya. Authentic dan build trust.",
                    platform: platform,
                    format: platform === 'Instagram' ? 'Feed Post' : 'Story',
                    confidence: 0.85
                },
                {
                    title: "Menu Harian + Harga",
                    description: "Bikin carousel atau slide menu hari ini lengkap dengan harga. Tambah 'Pesan sekarang sebelum kehabisan'.",
                    platform: platform,
                    format: 'Carousel',
                    confidence: 0.92
                }
            ],
            brand_awareness: [
                {
                    title: "Cerita Awal Usaha",
                    description: "Share story kenapa mulai usaha makanan ini. Personal touch yang bikin orang relate dan ingat brand.",
                    platform: platform,
                    format: 'Story Series',
                    confidence: 0.87
                },
                {
                    title: "Tips Masak Simple",
                    description: "Kasih tips masak sederhana yang relate dengan produk. Positioning sebagai ahli di bidang kuliner.",
                    platform: platform,
                    format: 'Educational Post',
                    confidence: 0.83
                },
                {
                    title: "Bahan Berkualitas",
                    description: "Showcase bahan-bahan segar yang dipakai. Highlight commitment terhadap kualitas dan kesehatan.",
                    platform: platform,
                    format: 'Video/Photo',
                    confidence: 0.88
                }
            ]
        },
        fashion: {
            jualan: [
                {
                    title: "OOTD dengan Produk",
                    description: "Bikin OOTD pakai produk yang dijual. Show different styling untuk satu item. Relatable dan inspiring.",
                    platform: platform,
                    format: 'Reels/Video',
                    confidence: 0.91
                },
                {
                    title: "Before After Styling",
                    description: "Tunjukkan transformasi outfit dari basic ke stylish pakai produk. Highlight versatility produk.",
                    platform: platform,
                    format: 'Transition Video',
                    confidence: 0.86
                },
                {
                    title: "Flash Sale Countdown",
                    description: "Bikin urgency dengan countdown timer untuk flash sale. Tampilkan best seller items dengan discount.",
                    platform: platform,
                    format: 'Story/Post',
                    confidence: 0.89
                }
            ]
        }
    };
    
    // Ambil ideas sesuai kategori, fallback ke ideas umum
    const categoryIdeas = baseIdeas[businessType] && baseIdeas[businessType][contentGoal] 
        ? baseIdeas[businessType][contentGoal]
        : [
            {
                title: "Konten Engaging Harian",
                description: `Buat konten ${contentGoal} yang sesuai dengan ${businessType} Anda. Fokus pada value dan engagement pelanggan.`,
                platform: platform,
                format: 'Multi Format',
                confidence: 0.75
            },
            {
                title: "User Generated Content",
                description: "Ajak pelanggan untuk share experience mereka. Repost dengan credit untuk build community.",
                platform: platform,
                format: 'UGC',
                confidence: 0.82
            },
            {
                title: "Educational Content",
                description: "Share knowledge atau tips yang relate dengan industri Anda. Build authority dan trust.",
                platform: platform,
                format: 'Educational',
                confidence: 0.79
            }
        ];
    
    // Simpan ke global variable untuk copy function
    window.currentIdeas = categoryIdeas;
    
    return categoryIdeas;
}

// Export functions untuk global access
window.initializeIdeasPage = initializeIdeasPage;
window.copyIdea = copyIdea;